### ISSUE TITLE
Moodle app expects 

### ISSUE THREAD

**Issue by cgs-ets** [moodlemobile/cordova-plugin-wkuserscript#2]
Moodle app expects WKUserScriptInjectionTime which was removed in the following commit:
https://github.com/moodlemobile/cordova-plugin-wkuserscript/commit/aa77d0f98a3fb106f2e798e5adf5882f01a2c947

Moodleapp > src/providers/utils/iframe.ts > line: 30:
import { WKUserScriptWindow, WKUserScriptInjectionTime } from 'cordova-plugin-wkuserscript';

Moodleapp no longer builds with latest cordova-plugin-wkuserscript.

**Comment by dpalou** [comment]
It has been fixed in the integration branch of the app, but it's not in the master branch yet. You can use this commit to fix it:

https://github.com/moodlehq/moodleapp/commit/b39c5ef909db509f7e5be0cccf2cffb66c0992f0
